import { registerEnumType } from '@nestjs/graphql'

export enum GqlNotificationType {
  POST_CREATED = 'POST_CREATED',
  COMMENT_CREATED = 'COMMENT_CREATED',
  ORDER_PAID = 'ORDER_PAID',
  PRODUCT_SOLD = 'PRODUCT_SOLD',
  FOLLOWED = 'FOLLOWED',
  ORDER_REFUNDED = 'ORDER_REFUNDED',
  ORDER_REFUNDED_FAILED = 'ORDER_REFUNDED_FAILED',
  ORDER_REFUNDED_SELLER = 'ORDER_REFUNDED_SELLER',
  INVOICE_PAID = 'INVOICE_PAID',
  SUBSCRIPTION_CANCEL_SCHEDULED = 'SUBSCRIPTION_CANCEL_SCHEDULED',
  SUBSCRIPTION_CANCELED = 'SUBSCRIPTION_CANCELED',
  SUBSCRIPTION_DELETED = 'SUBSCRIPTION_DELETED',
  LIKED = 'LIKED',
}

registerEnumType(GqlNotificationType, {
  name: 'NotificationType', // asta va apărea în schema GraphQL
  description: 'Notification type',
})