export enum ErrorCode {
  USERNAME_TAKEN = 'USERNAME_TAKEN',
  EMAIL_ALREADY_IN_USE = 'EMAIL_ALREADY_IN_USE',
  SLUG_TAKEN = 'SLUG_TAKEN',

  NOT_FOUND = 'NOT_FOUND',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}